<a href="https://colab.research.google.com/github/deividsantosjorge-dev/Economista_codando/blob/main/Scrap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q requests beautifulsoup4 lxml # instalando
print('Instalação feita com sucesso ✅')

Instalação feita com sucesso ✅

In [ ]:
import requests
from bs4 import BeautifulSoup

URL = "https://books.toscrape.com/"
res = requests.get(URL)
print("status_code:", res.status_code)

soup = BeautifulSoup(res.text)

status_code: 200

In [ ]:
livros = soup.find_all("article", class_="product_pod")
##print("Livros nesta página:", len(livros))

print("livros")

livros

In [ ]:
dados = []
for livro in livros:
    titulo = livro.find("h3").find("a")["title"]          # atributo title
    preco  = livro.find("p", class_="price_color").get_text(strip=True)
    # A classe star-rating tem 2 valores, ex.: ["star-rating", "Three"]
    nota = livro.find("p", class_="star-rating")["class"][1]
    estoque=livro.find("p", class_="availability").get_text(strip=True)


    #nota   = livro.find("p", class_="star-rating")["class"][1]
    #estoque = livro.find("p", class_="instock").get_text(strip=True)

    dados.append({"titulo": titulo, "preco": preco, "nota": nota, "estoque": estoque})
    print(f"{nota:5} | {preco} | {titulo:8} | {estoque:20}")

Three | Â£51.77 | A Light in the Attic | In stock
One   | Â£53.74 | Tipping the Velvet | In stock
One   | Â£50.10 | Soumission | In stock
Four  | Â£47.82 | Sharp Objects | In stock
Five  | Â£54.23 | Sapiens: A Brief History of Humankind | In stock
One   | Â£22.65 | The Requiem Red | In stock
Four  | Â£33.34 | The Dirty Little Secrets of Getting Your Dream Job | In stock
Three | Â£17.93 | The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull | In stock
Four  | Â£22.60 | The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics | In stock
One   | Â£52.15 | The Black Maria | In stock
Two   | Â£13.99 | Starving Hearts (Triangular Trade Trilogy, #1) | In stock
Four  | Â£20.66 | Shakespeare's Sonnets | In stock
Five  | Â£17.46 | Set Me Free | In stock
Five  | Â£52.29 | Scott Pilgrim's Precious Little Life (Scott Pilgrim #1) | In stock
Five  | Â£35.02 | Rip it Up and Start Again | In stock
Three | Â£57.25 | Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991 | In stock
One   | Â£23.88 | Olio     | In stock
One   | Â£37.59 | Mesaerion: The Best Science Fiction Stories 1800-1849 | In stock
Two   | Â£51.33 | Libertarianism for Beginners | In stock
Two   | Â£45.17 | It's Only the Himalayas | In stock

In [ ]:
import requests ## Biblioteca necessária para fazer a requisição HTTP (protocolo de comunicação da WEB)

### Aqui definino a URL onde tem alguns comentários de um livro em especifico
#URL = "https://www.amazon.com.br/Verity-Colleen-Hoover/dp/8501117846/ref=books_amz-books_desktop_mfs_bookzg_0?_encoding=UTF8&pd_rd_w=4Z6WS&content-id=amzn1.sym.f625a3aa-f530-41ef-9628-7b8cf479026b&pf_rd_p=f625a3aa-f530-41ef-9628-7b8cf479026b&pf_rd_r=BYV5KTC3X03WNJZ1ZB3Z&pd_rd_wg=6Ll2T&pd_rd_r=8baafb28-0429-4ab1-ba73-b76f4f9e4ecd"
#URL = "https://www.amazon.com.br/Verity-Colleen-Hoover/dp/8501117846"


#URL = "https://www.amazon.com.br/dp/B0CCL9VS9F/ref=sspa_dk_detail_2?psc=1&pf_rd_p=01db1132-7a41-4b6b-bb8e-16b3635a59d0&pf_rd_r=YKC68TCDBQRT7V62419T&pd_rd_wg=rQu4j&pd_rd_w=cnbE3&content-id=amzn1.sym.01db1132-7a41-4b6b-bb8e-16b3635a59d0&pd_rd_r=b573c028-136e-46d2-a6f7-a11e301f97e9&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw"
URL = "https://www.amazon.com.br/dp/B0CCL9VS9F"

#Como para extrair os comentários dos livros da amazom é necessário definir algumas informações adicionais (como em headers especificos, não bastantando definir a URL), crio uma variável para o header
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Safari/537.36 Edg/149.0.0.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Upgrade-Insecure-Requests": "1"
}


# Com o uso da biblioteca requests, faço a requisição do conteúdo da página criando uma variável "reque", usando o headers (especificidade da página da Amazom).
reque = requests.get(URL, headers=headers)

In [ ]:
#aqui eu testo para saber se a minha requisição contem reviewRichContentContaine, que é o que identifica os elementos que abriga os comentários.
#Se ele estiver lá, retornará True
print("reviewRichContentContainer" in reque.text)

True

In [ ]:
print(reque.status_code)
print(len(reque.text))

200
969731

In [ ]:

# Em seguida, importo a biblioteca BeautifulSoup,
# que será usada para interpretar e navegar pelo HTML recebido.
from bs4 import BeautifulSoup

# Transformo o HTML armazenado em reque.text em um objeto BeautifulSoup.
# O "html.parser" é o analisador que organiza esse HTML para que possamos localizar tags, atributos e textos.
#Basicamente, no BeautifulSoup a regra é: 1º argumento → conteúdo que será analisado e 2º argumento → parser que será utilizado
soup = BeautifulSoup(reque.text, "html.parser")

# Procuro no HTML todos os elementos que possuem data-hook="reviewRichContentContainer".
# O select() retorna uma lista com todos os elementos encontrados.
comentarios = soup.select('[data-hook="reviewRichContentContainer"]')

# Verifico quantos comentários foram encontrados.
print(len(comentarios))

8

In [ ]:
# Percorro cada elemento encontrado na lista "comentarios".
# enumerate() também cria uma numeração para cada comentário,
# começando em 1 por causa de start=1.
for i, comentario in enumerate(comentarios, start=1):

    # Extraio apenas o texto existente dentro do elemento HTML.
    # strip=True remove espaços e quebras de linha desnecessários.
    print(i, comentario.get_text(strip=True))

    # Imprime uma linha para separar visualmente os comentários.
    print("------------")

1 Sabe aquele clichê gostoso ? É esse . Uma história que mostra a força da nossa protagonista, que luta todos dias pra ter uma vida melhor . Tbm traz a luta de Cassius pra superar seus monstros e conseguir viver seu grande amor . No meu primeiro contato com a escrita da autora , ela me conquistou, um enredo envolvente, dinâmico. Simplesmente apaixonada 💓
------------
2 Eu adorei como foi essa estória de amor e superação. Gostei de como a autora colocou um tema importante, mas que não foi um foco  que não tirou o tema principal que o amor deles.Tem alguns erros de troca de nome , mas nada que prejudica o texto.e nem a leituraEnfim amei
------------
3 A estória é interessante, mas há varias trocas de nome dos personagens. Precisa fazer a revisão do texto, mas nada que  uma leitura do todo nao afaste a compreensão
------------
4 Parabéns autora, Ariela Pereira!O livro literalmente excelente, pois consegue abordar vários temas sensíveis como diferentes sociais, vícios, alteração de planos de futuro etc... Porém de uma forma muito bonita, aonde o amor vence todas as barreiras, aonde a borda que a família vem constituída se torna alicerce inabalável.Simplesmente fiquei encantada com o livro, e super recomendo!
------------
5 Um livro muito gostoso de ler.Cassius, um rapaz muito ingênuo e mimado, com uma mãe narcisista. Mas, também protetora e que ama muito o filho, termina interferindo e mudando o futuro do filho e da mulher que ele ama.Parabéns.
------------
6 História boa, mas muito cansativa o início...Gostei dos personagens, da interação entre todos os personagens,do desenvolvimento da história e do final.
------------
7 Uma estória realmente incrível, onde é tudo dosado de forma equilibrada. Romance claro que não pode faltar, ação, uma pitada de suspense, perdão e amor, a esse não poderia faltar de forma alguma. Amei muito mesmo, e super indico.
------------
8 Gostei bastante, a protagonista é muito forte, não se abala pelos obstáculos impostos, seus pais são maravilhosos. O casal é perfeito.Vale a pena a leitura.
------------

In [ ]:
#Agora que conseguimos extrair os comentários daquele livro, vamos criar um machine learning para analisar os comentários.
#Antes vou criar meus textos de treinamento com suas respectivas respostas

textos = [
    # positivos
    "livro excelente",
    "história maravilhosa",
    "amei muito esse livro",
    "leitura envolvente",
    "livro incrível e emocionante",
    "gostei bastante da história",
    "personagens muito bons",
    "final surpreendente",
    "super recomendo esse livro",
    "vale muito a pena ler",
    "história muito bem escrita",
    "livro perfeito",
    "amei os personagens",
    "leitura viciante",
    "livro muito interessante",

    # negativos
    "livro horrível",
    "história muito ruim",
    "não gostei do livro",
    "leitura cansativa",
    "livro muito chato",
    "personagens mal desenvolvidos",
    "final decepcionante",
    "não recomendo esse livro",
    "história confusa",
    "livro péssimo",
    "não gostei dos personagens",
    "leitura arrastada",
    "história sem graça",
    "livro decepcionante",
    "muito difícil de terminar",

    # neutros
    "livro razoável",
    "história mediana",
    "não achei bom nem ruim",
    "livro comum",
    "leitura regular",
    "algumas partes são boas e outras ruins",
    "gostei de algumas partes mas não de outras",
    "história interessante mas com alguns problemas",
    "livro ok",
    "não me surpreendeu",
    "tem pontos positivos e negativos",
    "leitura aceitável"
]

classes = [
    # positivos
    "positivo",
    "positivo",
    "positivo",
    "positivo",
    "positivo",
    "positivo",
    "positivo",
    "positivo",
    "positivo",
    "positivo",
    "positivo",
    "positivo",
    "positivo",
    "positivo",
    "positivo",

    # negativos
    "negativo",
    "negativo",
    "negativo",
    "negativo",
    "negativo",
    "negativo",
    "negativo",
    "negativo",
    "negativo",
    "negativo",
    "negativo",
    "negativo",
    "negativo",
    "negativo",
    "negativo",

    # neutros
    "neutro",
    "neutro",
    "neutro",
    "neutro",
    "neutro",
    "neutro",
    "neutro",
    "neutro",
    "neutro",
    "neutro",
    "neutro",
    "neutro"
]

In [ ]:
# aqui extraio a função que vai vectorizar os textos, ou seja, transformar palavras em numeros de vezes que eles aparecem dentro de matrizes
from sklearn.feature_extraction.text import CountVectorizer

#aqui defini uma variável para chamá-lo
vectorizar = CountVectorizer ()

In [ ]:
# aqui eu vetorizo meus dados de treino (transformar palavras em numeros de vezes que eles aparecem). Antes, com a "fit" eu ensino o vocabulario.
#se eu simplesmente pedir para printr ele vai aparecer em coordenadas (que é a forma como o CountVectorizer () de fato enxerga onde tem dados diferente de zero)

X_train = vectorizar.fit_transform(textos)
print(X_train)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 129 stored elements and shape (42, 72)>
  Coords	Values
  (0, 37)	1
  (0, 27)	1
  (1, 31)	1
  (1, 39)	1
  (2, 37)	1
  (2, 4)	1
  (2, 43)	1
  (2, 26)	1
  (3, 35)	1
  (3, 24)	1
  (4, 37)	1
  (4, 33)	1
  (4, 23)	1
  (5, 31)	1
  (5, 29)	1
  (5, 6)	1
  (5, 16)	1
  (6, 43)	1
  (6, 53)	1
  (6, 10)	1
  (7, 28)	1
  (7, 65)	1
  (8, 37)	1
  (8, 26)	1
  (8, 64)	1
  :	:
  (35, 62)	1
  (36, 29)	1
  (36, 46)	1
  (36, 17)	2
  (36, 2)	1
  (36, 50)	1
  (36, 49)	1
  (36, 40)	1
  (37, 31)	1
  (37, 34)	1
  (37, 40)	1
  (37, 13)	1
  (37, 3)	1
  (37, 56)	1
  (38, 37)	1
  (38, 47)	1
  (39, 46)	1
  (39, 41)	1
  (39, 66)	1
  (40, 68)	1
  (40, 54)	1
  (40, 55)	1
  (40, 44)	1
  (41, 35)	1
  (41, 0)	1

In [ ]:
#já esse aparece os nomes das palavras que foram aprendidados pelo CountVectorizer na mesma ordem das colunas.
print(vectorizar.get_feature_names_out())

['aceitável' 'achei' 'algumas' 'alguns' 'amei' 'arrastada' 'bastante'
 'bem' 'boas' 'bom' 'bons' 'cansativa' 'chato' 'com' 'comum' 'confusa'
 'da' 'de' 'decepcionante' 'desenvolvidos' 'difícil' 'do' 'dos'
 'emocionante' 'envolvente' 'escrita' 'esse' 'excelente' 'final' 'gostei'
 'graça' 'história' 'horrível' 'incrível' 'interessante' 'leitura' 'ler'
 'livro' 'mal' 'maravilhosa' 'mas' 'me' 'mediana' 'muito' 'negativos'
 'nem' 'não' 'ok' 'os' 'outras' 'partes' 'pena' 'perfeito' 'personagens'
 'pontos' 'positivos' 'problemas' 'péssimo' 'razoável' 'recomendo'
 'regular' 'ruim' 'ruins' 'sem' 'super' 'surpreendente' 'surpreendeu'
 'são' 'tem' 'terminar' 'vale' 'viciante']

In [ ]:
#aqui aparece em vetores numero de vezes como uma matriz comum incluindo os zeros
print(X_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]

In [ ]:
#aqui é só uma visualização
import pandas as pd

tabela = pd.DataFrame(
    X_train.toarray(),
    columns=vectorizar.get_feature_names_out()
)

tabela

,aceitável,achei,algumas,alguns,amei,arrastada,bastante,bem,boas,bom,...,ruins,sem,super,surpreendente,surpreendeu,são,tem,terminar,vale,viciante
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
10,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,0,0,1,0,0,0,0,0,1,0,...,1,0,0,0,0,1,0,0,0,0
36,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
41,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Importo o algoritmo de classificação Naive Bayes Multinomial
from sklearn.naive_bayes import MultinomialNB

#Só que matematicamente ele faz isso por meio de probabilidades, não simplesmente decorando "bom = positivo".
modelo = MultinomialNB()

modelo.fit(X_train, classes)

#COMENTÁRIO: O Naive Bayes é uma família de algoritmos de classificação baseada no teorema de Bayes. Ele tenta responder algo como:
#"Dadas as palavras que apareceram neste comentário, qual é a probabilidade de ele pertencer à classe positivo e qual é a probabilidade de pertencer à classe negativo?"

MultinomialNB()

In [ ]:
texto_amazom=[]
for comentario in comentarios:
  texto_amazom.append(comentario.get_text(strip=True))

In [ ]:
#crio o novo texto
#novo_texto = ["produto muito bom"]

In [ ]:
#trnsformo em matrizes
novo_texto_vec = vectorizar.transform(texto_amazom)

In [ ]:
#peço para ele fazer a preição
resultado = modelo.predict(novo_texto_vec)

print(resultado)

['positivo' 'neutro' 'negativo' 'negativo' 'positivo' 'negativo'
 'negativo' 'positivo']

In [ ]:
probabilidades = modelo.predict_proba(novo_texto_vec)

print(modelo.classes_)
print(probabilidades)

['negativo' 'neutro' 'positivo']
[[7.81218760e-02 1.20244973e-01 8.01633151e-01]
 [6.40745263e-03 9.93552619e-01 3.99286514e-05]
 [5.32910616e-01 4.10127264e-01 5.69621200e-02]
 [5.50812963e-01 1.02023554e-01 3.47163483e-01]
 [2.58849549e-01 6.99198539e-03 7.34158466e-01]
 [7.21610045e-01 4.34305703e-04 2.77955650e-01]
 [6.84514991e-01 1.94144621e-01 1.21340388e-01]
 [2.15124665e-01 4.90547084e-02 7.35820626e-01]]

In [ ]:


# aqui extraio a função que vai vectorizar os textos, ou seja, transformar palavras em numeros de vezes que eles aparecem dentro de matrizes
from sklearn.feature_extraction.text import CountVectorizer

#aqui defini uma variável para chamá-lo
vectorizar = CountVectorizer(ngram_range=(1, 2))

In [ ]:
X_train = vectorizar.fit_transform(textos)

In [ ]:
# Importo o algoritmo de classificação Naive Bayes Multinomial
from sklearn.naive_bayes import MultinomialNB

#Só que matematicamente ele faz isso por meio de probabilidades, não simplesmente decorando "bom = positivo".
modelo = MultinomialNB()

modelo.fit(X_train, classes)

#COMENTÁRIO: O Naive Bayes é uma família de algoritmos de classificação baseada no teorema de Bayes. Ele tenta responder algo como:
#"Dadas as palavras que apareceram neste comentário, qual é a probabilidade de ele pertencer à classe positivo e qual é a probabilidade de pertencer à classe negativo?"

MultinomialNB()

In [ ]:
texto_amazom=[]
for comentario in comentarios:
  texto_amazom.append(comentario.get_text(strip=True))

In [ ]:
#trnsformo em matrizes
novo_texto_vec = vectorizar.transform(texto_amazom)

In [ ]:
#peço para ele fazer a preição
resultado = modelo.predict(novo_texto_vec)

print(resultado)

['positivo' 'neutro' 'negativo' 'positivo' 'positivo' 'negativo'
 'negativo' 'positivo']

In [ ]:
probabilidades = modelo.predict_proba(novo_texto_vec)

print(modelo.classes_)
print(probabilidades)

['negativo' 'neutro' 'positivo']
[[7.94937495e-02 1.08208883e-01 8.12297367e-01]
 [3.95636837e-03 9.96019560e-01 2.40718931e-05]
 [5.91368691e-01 3.78262467e-01 3.03688421e-02]
 [4.18562427e-01 6.55662476e-02 5.15871325e-01]
 [2.64234985e-01 3.01812494e-03 7.32746890e-01]
 [7.37330164e-01 7.98407099e-05 2.62589996e-01]
 [6.30318061e-01 1.51191001e-01 2.18490938e-01]
 [1.26788007e-01 2.47868780e-02 8.48425115e-01]]

In [ ]:
import pandas as pd

tabela_resultados = pd.DataFrame(
    probabilidades,
    columns=modelo.classes_
)

tabela_resultados["previsao"] = resultado

tabela_resultados

   negativo    neutro  positivo  previsao
0  0.079494  0.108209  0.812297  positivo
1  0.003956  0.996020  0.000024    neutro
2  0.591369  0.378262  0.030369  negativo
3  0.418562  0.065566  0.515871  positivo
4  0.264235  0.003018  0.732747  positivo
5  0.737330  0.000080  0.262590  negativo
6  0.630318  0.151191  0.218491  negativo
7  0.126788  0.024787  0.848425  positivo